[FIX] l10n_mx_edi: Traceback ZeroDivisionError
Steps to reproduce the error:

- Create an invoice with quantity 0.0
- Validate

This will display a traceback:

```ZeroDivisionError: float division by zero

Error to render compiling AST
ZeroDivisionError: float division by zero
Template: l10n_mx_edi.cfdiv33
Path: /templates/t/cfdi:Comprobante/cfdi:Conceptos/t/cfdi:Concepto```

This is because in the template the 'ValorUnitario' field try to divide
by the quantity, which in this case is 0.0:

```t-att-ValorUnitario="'%.*f' % (decimal_precision,
subtotal_wo_discount(line)/line.quantity)"```

closes odoo/enterprise#3349