[FIX] l10n_mx_edi: fix 2 programming errors in _l10n_mx_edi_finkok_cancel()
(1) comparison between apples and oranges

    Attribute 'EstatusUUID' is a string, and is compared like integer

(2) variables definition out of scope

    The variable assign to 'code' and 'cancelled' is inside of else
    validation, if the response not hasattr('Folios'), this variables are
    not assigned, but are used to_l10n_mx_edi_post_cancel_process method.

    Without the patch, we may face the error:
    UnboundLocalError: local variable 'cancelled' referenced before
    assignment

Was PR #936. Courtesy of Luis Ernesto Torres Macías