[FIX] sale_ebay: res_config_settings.py requires sale_ebay.py
`sale_ebay.py` must be imported before `res_config_settings.py`
because of the default value of the field `res.config.settings.ebay_site`
which requires the model `ebay.site` to be installed during the creation
of the table `sale_ebay`.

Otherwise,the below traceback may be raised during the installation of
sale_ebay:

```
File "/home/odoo/src/enterprise/sale_ebay/models/res_config_settings.py", line 33, in <lambda>
  default=lambda self: self.env['ebay.site'].search([], limit=1).id,
...
...
psycopg2.ProgrammingError: relation "ebay_site" does not exist
LINE 1: SELECT "ebay_site".id FROM "ebay_site" ORDER BY "ebay_site"....
```

closes odoo/enterprise#4270

Signed-off-by: Denis Ledoux <beledouxdenis@users.noreply.github.com>