[FIX] l10n_mx_edi: unit test error when sign task#25809
Fixes errors to be able to install the module:

1. `['<p>The cfdi generated is not valid<
/p><ul><li>(":18:0:ERROR:SCHEMASV:SCHEMAV_CVC_COMPLEX_TYPE_4: Element
\'{http://www.sat.gob.mx/cfd/3}Traslado\': The attribute \'Impuesto\' is
require
d but missing.</li><li>:47:0:ERROR:SCHEMASV:SCHEMAV_CVC_COMPLEX_TYPE_4:
Element \'{http://www.sat.gob.mx/cfd/3}Traslado\': The attribute
\'Impuesto\'
is required but missing.", \'\')</li></ul>', '', '']']`

Because the `tag_ids` field is not being set inside the creation.

2. Element '<xpath expr="//div[@name='invoice_address']">' cannot be
located in parent view
Because invoice_address div does not exists anymore
[https://github.com/odoo/odoo/commit/c71da7db84f20ba8fb8c4da83d6a3ee063bb1c01#diff-774f4f512fb11d642b30d54aa5980f6b]

3. Agrolait partner no longer exists

4. 'NoneType' object has no attribute 'product_id' This error is throw
because of this change:
odoo/odoo@762aded#diff-774f4f512fb11d642b30d54aa5980f6bR90
Where "l" is changed by "line" in the loop.

5. 'NoneType' object has no attribute 'Receptor'

6. Element '<xpath expr=//thead/tr>' cannot be located in parent view

closes #2455

Co-authored-by: Nicolas Lempereur <nle@odoo.com>