[FIX] l10n_mx_edi: Fix runbot errors/warnings
1. Error in test related with empty values was fixed:
```
ERROR: new row for relation "account_invoice_line" violates check
constraint "account_invoice_line_accountable_required_fields"
DETAIL:  Failing row contains (12, , null, 10, 12, null, 8, null,
450.00, null, null, null, 1.000, 0.00, null, 1, null, null, f, null, 8,
2019-01-15 19:08:33.761115, 8, 2019-01-15 19:08:33.761115).
```
The translation to english has empty values, so the name, account_id and
uom_id where being reset for onchange_product_id.

2. Error in expected file (l10n_mx_edi_payment_bank module), because of the
rate changes over time, now write the rate to ensure that always will be
the expected value:

```
` -
'TipoCambioP': '14.540000',
` ?
^ ^^
`
` +
'TipoCambioP': '12.210000',
` ?
^ ^^
```

3. ``WARNING openerp_test odoo.addons.base.models.res_currency: The
`compute` method is deprecated. Use `_convert` instead``` was fixed.

closes odoo/enterprise#3454