[FIX] account_reports: code not converted during #290a4b04ad1ca5ebdfe4395546801df274505101
Print the difference for a journal raise a traceback, because AttributeError: 'str' object has no attribute 'get'

+ fix a comparing apple and orange comparison for selected company.