[FIX] account_bank_reconciliation_report: reconciliation report error
Here in account_reports/models/account_bank_reconciliation_report.py
after the query is executed the fetchone() only return a 'None' value, so
'start_amount' will be 'None, and the error is displayed.

The start_amount must have some value even when fetchone() is None, so
it could be something this like:

start_amount = self._cr.fetchone()[0] or 0.0

'
Steps to reproduce:

Video:
https://drive.google.com/file/d/1FeOuPGiaK_Hwfhz0q6gyA7bnK5f81fR0/view

Tested in http://526923-11-0-debc7a.runbot16.odoo.com

Current behavior:

The following error is shown when try to print the report

```
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

Expected behavior:

Display the Conciliation report

closes odoo/enterprise#4439

Signed-off-by: Quentin De Paoli (qdp) <qdp@openerp.com>